name: CI

on: [push]

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable pnpm

      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: 18

      - run: pnpm install --frozen-lockfile
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome ci .

      - name: Run tests
        run: pnpm test:coverage && pnpm test:report
      - name: Coveralls
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage.lcov